name: Deploy neccessary components to EKS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Install kubectl
        uses: azure/setup-kubectl@776406bce94f63e41d621b960d78ee25c8b76ede

      - name: Install Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get AWS caller identity
        id: caller-identity
        run: |
          CALLER_IDENTITY=$(aws sts get-caller-identity)
          echo "Caller Identity: $CALLER_IDENTITY"
          ACCOUNT_ID=$(echo $CALLER_IDENTITY | jq -r '.Account')
          echo "Account ID: $ACCOUNT_ID"
          echo "account_id=$ACCOUNT_ID" >> $GITHUB_OUTPUT

      - name: Assume role
        id: assume-role
        run: |
          ROLE_ARN="arn:aws:iam::${{ steps.caller-identity.outputs.account_id }}:role/GithubActions"
          SESSION_NAME="actions-build-${{ github.run_id }}"

          echo "Assuming role: $ROLE_ARN"
          echo "Session name: $SESSION_NAME"

          CREDENTIALS=$(aws sts assume-role \
            --role-arn $ROLE_ARN \
            --role-session-name $SESSION_NAME \
            --output json)

          AWS_ACCESS_KEY_ID=$(echo "$CREDENTIALS" | jq -r '.Credentials.AccessKeyId')
          AWS_SECRET_ACCESS_KEY=$(echo "$CREDENTIALS" | jq -r '.Credentials.SecretAccessKey')
          AWS_SESSION_TOKEN=$(echo "$CREDENTIALS" | jq -r '.Credentials.SessionToken')

          echo "::add-mask::$AWS_ACCESS_KEY_ID"
          echo "::add-mask::$AWS_SECRET_ACCESS_KEY"
          echo "::add-mask::$AWS_SESSION_TOKEN"

          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" >> $GITHUB_ENV

          echo "Role assumed and credentials configured"

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --name mlsecops-eks-cluster \
            --region us-east-1
          echo "Kubeconfig updated for mlsecops-eks-cluster"

      - name: Verify cluster access
        run: |
          echo "Checking cluster nodes..."
          kubectl get nodes
          echo ""
          echo "Successfully connected to EKS cluster"

      - name: Install ArgoCD
        run: |
          chmod +x scripts/install-argo-cd.sh
          ./scripts/install-argo-cd.sh
